version: '3.3'

networks:
    symfony:

volumes:
    database:
    symfony:

services:
    db:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
        networks:
            - symfony
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        image: hello-symfony
        volumes:
            - symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
        networks:
            - symfony
        depends_on:
            - db

    nginx:
        build: nginx
        ports:
            - 80:80
        volumes:
            - symfony:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx
        networks:
            - symfony
        depends_on:
            - php
